language: bash
services: docker

env:
  - VERSION=master VARIANT=
  - VERSION=master VARIANT=alpine
  - VERSION=19 VARIANT=
  - VERSION=19 VARIANT=slim
  - VERSION=18 VARIANT=
  - VERSION=18 VARIANT=slim

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="$(awk '$1 == "FROM" { print $2; exit }' onbuild/Dockerfile)${VARIANT:+-$VARIANT}"

script:
  - docker build --pull -t "$image" "${VARIANT:-.}"
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images
